### PR TITLE
Ability to provide path to get the ops files from

### PR DESCRIPTION
**Pull request by mathewparet**
This enhancement provides an extra parameter to the `operations:show` and `operations:process` commands to allow user to specify the path the operations files can be loaded from.

### CODE REVIEW

**Comment by mathewparet** [comment]
Sorry for the mess about the last 2 commits. But now this Pull request is good to go. I've tested it.

**Comment by mathewparet** [comment]
That's all the commits. I'm sorry for the mess of submitting multiple commits to this pull request after it was originally raised. This is the first time I'm working on a pull request. I've tested all possible scenarios I could think off and it works fine now.

Enhancements so far:

1. Added `--path` option to `operations:show` and `operations:process` so that you can load operations from a custom path.
2. Added `--database` option to `operations:process` so that you can specify the database connection against which the operations should be run.

**Comment by mathewparet** [comment]
Support for `--job` flag so that the process job class can be overridden while running `operations:process` command. This is useful, say in case you wish to implement operations for a multi-tenancy setup using `spatie/laravel-multitenancy`. Most multi-tenancy packages require you to implement a special interface for jobs so that they can be tagged as a tenant job. This change provides support for that so that the developer can extend the `OneTimeOperationProcessJob` job and add a the required implementation of the TenantAware (or similar) interface so that the jobs run in tenancy.

**Comment by TimoKoerber** [comment]
Thank you for your contribution. I know what you were going for, but I don't like the execution. Your PR applies so many changes that I can't even comprehend them. I want this package to be as simple as possible and not a "Jack of all trades". But feel free to create a Fork for this.

**Pull request closed without merging**
